<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Resource\fonts\" />
      <Folder Include="Resource\img\" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Resource\img\mtHollyBackground.png" />
      <Resource Include="Resource\img\mtHollyBackground.png" />
      <None Remove="Resource\fonts\Dosis-Medium.ttf" />
      <Resource Include="Resource\fonts\Dosis-Medium.ttf" />
    </ItemGroup>

</Project>
